"""create initial schema

Revision ID: b8ef9b6eac65
Revises: 
Create Date: 2026-08-03 14:30:33.409215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8ef9b6eac65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.Enum('USER', 'TECHNICIAN', 'ADMIN', name='user_role'), server_default='USER', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(btrim(full_name)) > 0', name=op.f('ck_users_full_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.BigInteger(), nullable=True),
    sa.Column('result', sa.Enum('SUCCESS', 'FAILURE', 'DENIED', name='audit_result'), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            resource_type IS NULL\n            OR char_length(btrim(resource_type)) BETWEEN 1 AND 50\n            ', name=op.f('ck_audit_logs_resource_type_length')),
    sa.CheckConstraint('char_length(btrim(event_type)) BETWEEN 1 AND 80', name=op.f('ck_audit_logs_event_type_length')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_audit_logs_user_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_audit_logs_event_type', 'audit_logs', ['event_type'], unique=False)
    op.create_index('ix_audit_logs_user_created_at', 'audit_logs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('SUPPORT', 'SECURITY', 'ACCESS', 'ANOMALY', 'DATA', name='incident_category'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incident_priority'), server_default='MEDIUM', nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='incident_status'), server_default='OPEN', nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_to_id', sa.BigInteger(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            (\n                status IN ('OPEN', 'IN_PROGRESS')\n                AND resolution IS NULL\n                AND resolved_at IS NULL\n                AND closed_at IS NULL\n            )\n            OR\n            (\n                status = 'RESOLVED'\n                AND resolution IS NOT NULL\n                AND char_length(btrim(resolution)) > 0\n                AND resolved_at IS NOT NULL\n                AND closed_at IS NULL\n            )\n            OR\n            (\n                status = 'CLOSED'\n                AND resolution IS NOT NULL\n                AND char_length(btrim(resolution)) > 0\n                AND resolved_at IS NOT NULL\n                AND closed_at IS NOT NULL\n            )\n            ", name=op.f('ck_incidents_status_dates')),
    sa.CheckConstraint("\n            status = 'OPEN'\n            OR assigned_to_id IS NOT NULL\n            ", name=op.f('ck_incidents_assignment_before_processing')),
    sa.CheckConstraint('\n            closed_at IS NULL\n            OR (\n                resolved_at IS NOT NULL\n                AND closed_at >= resolved_at\n            )\n            ', name=op.f('ck_incidents_closed_after_resolution')),
    sa.CheckConstraint('\n            resolution IS NULL\n            OR char_length(btrim(resolution)) BETWEEN 1 AND 5000\n            ', name=op.f('ck_incidents_resolution_length')),
    sa.CheckConstraint('\n            resolved_at IS NULL\n            OR resolved_at >= created_at\n            ', name=op.f('ck_incidents_resolved_after_creation')),
    sa.CheckConstraint('char_length(btrim(description)) BETWEEN 10 AND 5000', name=op.f('ck_incidents_description_length')),
    sa.CheckConstraint('char_length(btrim(title)) BETWEEN 5 AND 150', name=op.f('ck_incidents_title_length')),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name='fk_incidents_assigned_to_id_users', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_incidents_created_by_id_users', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents')),
    sa.UniqueConstraint('reference', name=op.f('uq_incidents_reference'))
    )
    op.create_index('ix_incidents_assigned_status_priority', 'incidents', ['assigned_to_id', 'status', sa.literal_column('priority DESC'), sa.literal_column('created_at ASC')], unique=False)
    op.create_index('ix_incidents_created_by_created_at', 'incidents', ['created_by_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('incident_comments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('incident_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(btrim(content)) BETWEEN 1 AND 5000', name=op.f('ck_incident_comments_content_length')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='fk_incident_comments_author_id_users', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='fk_incident_comments_incident_id_incidents', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_comments'))
    )
    op.create_index('ix_incident_comments_incident_created_at', 'incident_comments', ['incident_id', 'created_at'], unique=False)
    op.create_table('incident_history',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('incident_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.Enum('INCIDENT_CREATED', 'ASSIGNED', 'REASSIGNED', 'PRIORITY_CHANGED', 'STATUS_CHANGED', 'COMMENT_ADDED', 'RESOLVED', 'CLOSED', name='incident_history_action'), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            field_name IS NULL\n            OR char_length(btrim(field_name)) BETWEEN 1 AND 50\n            ', name=op.f('ck_incident_history_field_name_length')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name='fk_incident_history_actor_id_users', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='fk_incident_history_incident_id_incidents', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_history'))
    )
    op.create_index('ix_incident_history_incident_created_at', 'incident_history', ['incident_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incident_history_incident_created_at', table_name='incident_history')
    op.drop_table('incident_history')
    op.drop_index('ix_incident_comments_incident_created_at', table_name='incident_comments')
    op.drop_table('incident_comments')
    op.drop_index('ix_incidents_created_by_created_at', table_name='incidents')
    op.drop_index('ix_incidents_assigned_status_priority', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_audit_logs_user_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_event_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
