-- PostgreSQL schema v1
-- Plateforme DevSecOps de gestion d'incidents
-- Ce fichier sert de modèle physique de référence.
-- Les migrations Alembic deviendront ensuite la source de vérité du projet.

BEGIN;

CREATE TYPE user_role AS ENUM ('USER', 'TECHNICIAN', 'ADMIN');

CREATE TYPE incident_status AS ENUM (
    'OPEN',
    'IN_PROGRESS',
    'RESOLVED',
    'CLOSED'
);

CREATE TYPE incident_priority AS ENUM (
    'LOW',
    'MEDIUM',
    'HIGH',
    'CRITICAL'
);

CREATE TYPE incident_category AS ENUM (
    'SUPPORT',
    'SECURITY',
    'ACCESS',
    'ANOMALY',
    'DATA'
);

CREATE TYPE incident_history_action AS ENUM (
    'INCIDENT_CREATED',
    'ASSIGNED',
    'REASSIGNED',
    'PRIORITY_CHANGED',
    'STATUS_CHANGED',
    'COMMENT_ADDED',
    'RESOLVED',
    'CLOSED'
);

CREATE TYPE audit_result AS ENUM ('SUCCESS', 'FAILURE', 'DENIED');

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    role user_role NOT NULL DEFAULT 'USER',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_full_name_not_blank
        CHECK (char_length(btrim(full_name)) > 0)
);

CREATE UNIQUE INDEX uq_users_email_lower
    ON users (lower(email));

CREATE SEQUENCE incident_reference_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(20) NOT NULL UNIQUE
        DEFAULT (
            'INC-' ||
            lpad(nextval('incident_reference_seq')::text, 6, '0')
        ),
    title VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    category incident_category NOT NULL,
    priority incident_priority NOT NULL DEFAULT 'MEDIUM',
    status incident_status NOT NULL DEFAULT 'OPEN',
    created_by_id BIGINT NOT NULL,
    assigned_to_id BIGINT NULL,
    resolution TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ NULL,
    closed_at TIMESTAMPTZ NULL,

    CONSTRAINT fk_incidents_created_by
        FOREIGN KEY (created_by_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_incidents_assigned_to
        FOREIGN KEY (assigned_to_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_incidents_title_length
        CHECK (char_length(btrim(title)) BETWEEN 5 AND 150),

    CONSTRAINT ck_incidents_description_length
        CHECK (char_length(btrim(description)) BETWEEN 10 AND 5000),

    CONSTRAINT ck_incidents_resolution_length
        CHECK (
            resolution IS NULL
            OR char_length(btrim(resolution)) BETWEEN 1 AND 5000
        ),

    CONSTRAINT ck_incidents_assignment_before_processing
        CHECK (
            status = 'OPEN'
            OR assigned_to_id IS NOT NULL
        ),

    CONSTRAINT ck_incidents_status_dates
        CHECK (
            (
                status IN ('OPEN', 'IN_PROGRESS')
                AND resolution IS NULL
                AND resolved_at IS NULL
                AND closed_at IS NULL
            )
            OR
            (
                status = 'RESOLVED'
                AND resolution IS NOT NULL
                AND char_length(btrim(resolution)) > 0
                AND resolved_at IS NOT NULL
                AND closed_at IS NULL
            )
            OR
            (
                status = 'CLOSED'
                AND resolution IS NOT NULL
                AND char_length(btrim(resolution)) > 0
                AND resolved_at IS NOT NULL
                AND closed_at IS NOT NULL
            )
        ),

    CONSTRAINT ck_incidents_resolved_after_creation
        CHECK (
            resolved_at IS NULL
            OR resolved_at >= created_at
        ),

    CONSTRAINT ck_incidents_closed_after_resolution
        CHECK (
            closed_at IS NULL
            OR (
                resolved_at IS NOT NULL
                AND closed_at >= resolved_at
            )
        )
);

ALTER SEQUENCE incident_reference_seq
    OWNED BY incidents.reference;

CREATE TABLE incident_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_comments_incident
        FOREIGN KEY (incident_id)
        REFERENCES incidents(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_comments_author
        FOREIGN KEY (author_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_comments_content_length
        CHECK (char_length(btrim(content)) BETWEEN 1 AND 2000)
);

CREATE TABLE incident_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id BIGINT NOT NULL,
    actor_id BIGINT NOT NULL,
    action incident_history_action NOT NULL,
    field_name VARCHAR(50) NULL,
    old_value TEXT NULL,
    new_value TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_history_incident
        FOREIGN KEY (incident_id)
        REFERENCES incidents(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_history_actor
        FOREIGN KEY (actor_id)
        REFERENCES users(id)
        ON DELETE RESTRICT
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL,
    event_type VARCHAR(80) NOT NULL,
    resource_type VARCHAR(50) NULL,
    resource_id BIGINT NULL,
    result audit_result NOT NULL,
    ip_address INET NULL,
    user_agent TEXT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_logs_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE SET NULL,

    CONSTRAINT ck_audit_event_type_not_blank
        CHECK (char_length(btrim(event_type)) > 0)
);

CREATE INDEX ix_incidents_created_by_created_at
    ON incidents (created_by_id, created_at DESC);

CREATE INDEX ix_incidents_assigned_status_priority
    ON incidents (
        assigned_to_id,
        status,
        priority DESC,
        created_at ASC
    );

CREATE INDEX ix_incident_comments_incident_created_at
    ON incident_comments (incident_id, created_at ASC);

CREATE INDEX ix_incident_history_incident_created_at
    ON incident_history (incident_id, created_at DESC);

CREATE INDEX ix_audit_logs_created_at
    ON audit_logs (created_at DESC);

CREATE INDEX ix_audit_logs_user_created_at
    ON audit_logs (user_id, created_at DESC);

CREATE INDEX ix_audit_logs_event_type
    ON audit_logs (event_type);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_incidents_set_updated_at
BEFORE UPDATE ON incidents
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMIT;
